version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
  pre_build:
    commands:
      - npm install ejs 
      - npm install path 
      - npm install express 
  build:
    commands:
  post_build:
    commands:
      - echo Build completed on `date`
